name: .NET Core

on: push

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: 2.1.809
    - name: dotnet clean
      run: |  
          cd src
          dotnet clean
    - name: dotnet build
      run: |
          cd src
          $branch = @($env:GITHUB_REF -split "/")[-1]
          if($branch -eq "master")
          {
            dotnet build --configuration Release
          }else {
            $runNumber = $env:GITHUB_RUN_NUMBER
            dotnet build --configuration Release --version-suffix "$branch$runNumber"
          }
      shell: pwsh
    - name: dotnet pack
      run: |  
          cd src
          dotnet pack --no-build --configuration Release -o out
    - name: publish to nuget
      run: | 
          dotnet nuget push ./src/out/CoreSaml2Utils.*.nupkg -k ${{ secrets.Nuget_tristan }} -s https://api.nuget.org/v3/index.json
